### ISSUE TITLE
ctags job failed, returned: 1

### ISSUE THREAD

**Issue by jhogendorn** [ludovicchabant/vim-gutentags#169]
I'm getting the above message on BufWrite. A tag file is getting generated. I've tried running with `let g:gutentags_trace = 1` but thats not giving me any useful error message as to why ctags might be failing.

What steps can I take to debug this?

**Comment by aquatix** [comment]
I encounter the same thing, anything we can do to help?

**Comment by Nemermel** [comment]
@jhogendorn What is the output of trace?

**Comment by noboruma** [comment]
Maybe related to #177?

**Comment by aquatix** [comment]
Interesting find, but I don't have a list_command specified in my vimrc. Only config I have is the following:

    Plugin 'ludovicchabant/vim-gutentags'
    set statusline+=%{gutentags#statusline()}
    let g:gutentags_ctags_exclude = ["*.min.js", "*.min.css", "build", "vendor", ".git", "node_modules", "*.vim/bundle/*"]

**Comment by Nemermel** [comment]
@aquatix, Do you have ctags-exuberant on your system?
I had same thing without it. And also, it would be nice to see trace when gutentags causes error.

**Comment by aquatix** [comment]
Yes, that's the ctags version I'm using. Will try to get a trace.

**Comment by sittim** [comment]
I have been getting this issue as well...

**Comment by Nemermel** [comment]
So, is this issue still exist?
If so. please show the trace. You can enable it by:
```
let g:gutentags_trace = 1
```

**Comment by d3rhans** [comment]
Same problem here. I'm using the plugin in its default configuration. Trace output right after saving a file (in a latex project) is:

`gutentags: Running: ['~/.vim/bundle/vim-gutentags/plat/unix/update_tags.sh', '-e', 'ctags', '-t', 'tags', '-p', '.', '-s', 'doc/', '-o', '~/.vim/bundle/vim-gutentags/res/ctags_recursive.options', '-l', 'tags.log']
`
Note that I altered the path names slightly in the output.

I've executed the script with the parameters given by the trace and it stops with an error message:

ctags: "tags.temp" doesn't look like a tag file; I refuse to overwrite it.

And indeed, looking in the tag file, the first three lines are clobbered with some artifacts from the files in the project:


```
		frametitle{Some title     some_tex_file.tex	/^	}$/;"	u
	frame{
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME	Exuberant Ctags	//
!_TAG_PROGRAM_URL	http://ctags.sourceforge.net	/official site/
!_TAG_PROGRAM_VERSION	5.9~svn20110310	//
```

After that the file looks rather normal. I'll have a deeper look on how this happens this evening.

**Comment by d3rhans** [comment]
So I checked a bit more in detail. At least in my case, the problem seems to be caused by exuberant-ctags, not by gutentags. If I run a ctags -R . in the directory in question manually, without vim or gutentags running.

I can reproduce this issue on this single source directory, but not on others, furthermore it seems only to be an issue on my Ubuntu machine at work, but not on my Fedora machine at home. I'll check that in detail and report upstream if necessary.

@jhogendorn, @aquatix could you check, if in your case the error is also caused by a similar corrupted tag file?

**Comment by ludovicchabant** [comment]
Wow that's pretty random :)   Thanks for investigating. I guess we should find a way to better report that the `tags` file is corrupted (by maybe bubbling up the "_"tags.temp" doesn't look like a tag file; I refuse to overwrite it._" message to Vim).

**Comment by d3rhans** [comment]
Just in case anyone cares, this sort of issue with ctags was reported 6 years ago and is still open

https://sourceforge.net/p/ctags/bugs/332/

there is a similar ticket for some javascript. Seems there is no active development on ctags for some time now.

@ludovicchabant  The message would be good to have (or in general a more verbose error message, if the job fails), at least as option.

**Comment by aquatix** [comment]
@ludovicchabant yeah, having the ctags messages bubble up, would help, as it's way more clear for the user that it's something that's bugging ctags, not vim-gutentags.

@d3rhans OK, that's slightly bad indeed. I hope someone feels irked enough to take up active development again (no, I won't take another pet project ;)).

Thanks all for investigating, would not have found the solution so easily without the various pointers.

**Comment by x1314aq** [comment]
I have the same problem.

`.vimrc`
```vim
114 let g:gutentags_project_root = ['.git', '.svn', '.root', '.hg', '.project']
115 let g:gutentags_ctags_tagfile = '.tags'
116 let s:vim_tags = expand('~/.cache/tags')
117 let g:gutentags_cache_dir = s:vim_tags
118 let g:gutentags_ctags_extra_args = ['--fields=+niazS', '--extra=+q', '--c++-kinds=+px', '--c-kinds=+px']
119 let g:gutentags_trace = 1
120 let g:gutentags_file_list_command = {
121             \  'markers': {
122                 \  '.git': 'git ls-files',
123                 \  '.hg': 'hg files',
124                 \  }
125             \  }
```

`:messages` outputs
```
gutentags: [job output]: ['Locking tags file...', 'Running file list command, patching for absolute paths', 'eval git ls-files', 'Running ctags on whole project', 'cta
gs -f "/root/.cache/tags/root-dmm-normalized-leibnize-.tags.temp"  --fields=+niazS --extra=+q --c++-kinds=+px --c-kinds=+px --exclude=@ -L /root/.cache/tags/root-dmm-n
ormalized-leibnize-.tags.files', '']
gutentags: [job output]: ['ctags: Warning: --extra option is obsolete; use --extras instead', 'ctags: cannot open "" : No such file or directory', '']
gutentags: [job output]: ['']
gutentags: [job output]: ['']
gutentags: Finished ctags job.
gutentags: gutentags: ctags job failed, returned: 1
```

BTW, I'm using `universe-ctags` instead of `exuberant-ctags`.

**Comment by taq** [comment]
Just found that the command being run is something like:

```
update_tags.sh -e ctags -t tags -p . -x @ -l tags.log                        
Locking tags file...
Running ctags on whole project
ctags -f "tags.temp"  --exclude=@ .
ctags: cannot open "" : No such file or directory
```
The problem there is `-x @`. Running without it it runs ok:

```
update_tags.sh -e ctags -t tags -p . -l tags.log
Locking tags file...
Running ctags on whole project
ctags -f "tags.temp"  .
Replacing tags file
mv -f "tags.temp" "tags"
Unlocking tags file...
Done.
```
Seems it runs ctags like:

```
ctags -f "tags.temp"  --exclude=@
```
But on the ctags man page, it specifies that

```
If  pattern begins with the character '@', then the rest of the string is interpreted as a file name from which to read exclusion patterns, one per line.
```
There is no rest of the string after the `@` char, so I think it should be avoided?

**Comment by ludovicchabant** [comment]
Yep, sorry, I introduced that bug with a change yesterday -- you most likely get this bug if your `wildignore` is empty. I just pushed 713044e280792d29403fbcab3e477d790ef32eb8 to fix this!

**Comment by dmitriyK1** [comment]
@ludovicchabant Unfortunately I still have this bug with the latest version of the plugin

**Comment by yuanren10** [comment]
Here are what my log output:
-----------------------------------------------
gutentags: gutentags: ctags job failed, returned: 1
gutentags: Tracing is enabled.
"mm/migrate.c" 1863L, 48196C written
gutentags: Wildignore options file is up to date.
gutentags: Running: ['/home/yuanren/.vim/bundle/vim-gutentags/plat/unix/update_tags.sh', '-e', 'ctags', '-t', '/home/yuanren/.cache/tags/home-yuanren-runninglinuxkernel_4.0-
.tags', '-p', '/home/yuanren/runninglinuxkernel_4.0', '-L', 'find arch/arm/ mm/ kernel/ include/ init/ lib/', '-O', '--fields=+niazS --extra=+q --c++-kinds=+pxI --c-kinds=+p
x', '-l', '/home/yuanren/.cache/tags/home-yuanren-runninglinuxkernel_4.0-.tags.log']
gutentags: In:      /home/yuanren/runninglinuxkernel_4.0
gutentags: [job output]: 'Locking tags file...'
gutentags: [job output]: 'Running file list command, patching for absolute paths'
gutentags: [job output]: 'eval find arch/arm/ mm/ kernel/ include/ init/ lib/'
gutentags: [job output]: 'Running ctags on whole project'
gutentags: [job output]: 'ctags -f "/home/yuanren/.cache/tags/home-yuanren-runninglinuxkernel_4.0-.tags.temp"  --fields=+niazS --extra=+q --c++-kinds=+pxI --c-kinds=+px -L /
home/yuanren/.cache/tags/home-yuanren-runninglinuxkernel_4.0-.tags.files'
gutentags: [job output]: 'ctags: unrecognized option ''--fields=+niazS'''
gutentags: [job output]: '^ITry ''ctags --help'' for a complete list of options.'
gutentags: Finished ctags job.
gutentags: gutentags: ctags job failed, returned: 1

**Comment by ludovicchabant** [comment]
Notice how it says `ctags: unrecognized option ''--fields=+niazS"'`. Do you have a `.ctagsrc` or `.gutctags` or other place where you specified this option? Most likely you're using a version of `ctags` that doesn't support these field types?

**Comment by wviana** [comment]
Hi there, was it already patched? 
I'm getting
```
gutentags: Wildignore options file is up to date.
gutentags: Running: ['/Users/wviana/.vim/plugged/vim-gutentags/plat/unix/update_tags.sh', '-e', 'ctags', '-t', 'tags', '-p', '.', '-o', '/Users/wviana/.vim/plugged/vim-gutentags/res/ctags_recursive.options', '-x', '@/var/folders/6q/kby204
dx70z6k_k6_66m_tqm0000gn/T/vND6xnx/11', '-l', 'tags.log']
gutentags: ctags job failed, returned: 1
```

When it get fix will it be on master.

**Comment by sagotsky** [comment]
Got this in MacOS too.  I think it's because the system ctags was in my path before exuberant ctags from homebrew.  `chmod -x /usr/bin/ctags` made the error go away.

**Comment by snipem** [comment]
I had no ctags installed at all on one of my machines on MacOS. And I got the same error. `brew install ctags` solved the issue.

**Comment by wviana** [comment]
I've tried to remove execution as @sagotsky said. But probably the macos system protection don't allow to change it.

So as I nottice that my problems was about vim not calling a compatible ctags (exuberant or universal),  I'v tried to re-install and relink with brew, almost the same as @snipem suggested, but with no sucess to me.

So my sollution what to add this line on my vimrc

`let g:gutentags_ctags_executable = '/usr/local/Cellar/universal-ctags/HEAD-9630c39/bin/ctags'`

this variable is on gutentags documentation. So I just placed the fullpath to ctags that I want it to run.

Hope to help others.

PS: If I've written something wrong please tell me, so I may learn and correct, as english is not my first language.

**Comment by ludovicchabant** [comment]
@snipem : in theory, Gutentags checks for the case where `ctags` is not installed at all. See [this line](https://github.com/ludovicchabant/vim-gutentags/blob/master/autoload/gutentags/ctags.vim#L61), which is followed by a user-friendly message about the problem. Did you not get that error then?

@wviana to make it slightly prettier, and handle the case where you'll run `brew upgrade`, you could make it point to `/usr/local/bin/ctags` instead (by default, `brew` makes that a symlink to the last installed version)

**Comment by SurpassAll** [comment]
I'm gettting
```
gutentags: Wildignore options file is up to date.
gutentags: Running: ['/Users/linyue/.config/nvim/plugged/vim-gutentags/plat/unix/update_tags.sh', '-e', '/usr/local/opt/universal-ctags/bin/ctags', '-t', '/Users/linyue/.cache/tags/Users-linyue-WorkStation-golang_dev-src-git.inke.c
n-BackendPlatform-golang-.tags', '-p', '/Users/linyue/WorkStation/golang_dev/src/git.inke.cn/BackendPlatform/golang', '-s', '/Users/linyue/WorkStation/golang_dev/src/git.inke.cn/BackendPlatform/golang/kafka/consumer.go', '-o', '/Us
ers/linyue/.config/nvim/plugged/vim-gutentags/res/ctags_recursive.options', '-O', '--fields=+niazS --extra=+q --c++-kinds=+px --c-kinds=+px --output-format=e-ctags', '-x', '@/Users/linyue/.cache/tags/_wildignore.options', '-l', '/U
sers/linyue/.cache/tags/Users-linyue-WorkStation-golang_dev-src-git.inke.cn-BackendPlatform-golang-.tags.log']
gutentags: In:      /Users/linyue/WorkStation/golang_dev/src/git.inke.cn/BackendPlatform/golang
gutentags: Tag file '/Users/linyue/.cache/tags/Users-linyue-WorkStation-golang_dev-src-git.inke.cn-BackendPlatform-golang-.tags' is already being updated. Queuing it up...
gutentags: Running: ['gtags', '--incremental', '/Users/linyue/.cache/tags/Users-linyue-WorkStation-golang_dev-src-git.inke.cn-BackendPlatform-golang']
gutentags: In:      /Users/linyue/WorkStation/golang_dev/src/git.inke.cn/BackendPlatform/golang
gutentags:
gutentags: [job output]: ['Locking tags file...', 'Removing references to: /Users/linyue/WorkStation/golang_dev/src/git.inke.cn/BackendPlatform/golang/kafka/consumer.go', 'grep --text -Ev ''^[^^I]+^I/Users/linyue/WorkStation/golang
_dev/src/git.inke.cn/BackendPlatform/golang/kafka/consumer.go^I'' ''/Users/linyue/.cache/tags/Users-linyue-WorkStation-golang_dev-src-git.inke.cn-BackendPlatform-golang-.tags'' > ''/Users/linyue/.cache/tags/Users-linyue-WorkStation
-golang_dev-src-git.inke.cn-BackendPlatform-golang-.tags.temp''', 'Running ctags on "/Users/linyue/WorkStation/golang_dev/src/git.inke.cn/BackendPlatform/golang/kafka/consumer.go"', '/usr/local/opt/universal-ctags/bin/ctags -f "/Us
ers/linyue/.cache/tags/Users-linyue-WorkStation-golang_dev-src-git.inke.cn-BackendPlatform-golang-.tags.temp"  --options=/Users/linyue/.config/nvim/plugged/vim-gutentags/res/ctags_recursive.options --fields=+niazS --extra=+q --c++-
kinds=+px --c-kinds=+px --output-format=e-ctags --exclude=@/Users/linyue/.cache/tags/_wildignore.options --append "/Users/linyue/WorkStation/golang_dev/src/git.inke.cn/BackendPlatform/golang/kafka/consumer.go"', 'Replacing tags fil
e', 'mv -f "/Users/linyue/.cache/tags/Users-linyue-WorkStation-golang_dev-src-git.inke.cn-BackendPlatform-golang-.tags.temp" "/Users/linyue/.cache/tags/Users-linyue-WorkStation-golang_dev-src-git.inke.cn-BackendPlatform-golang-.tag
s"', 'Unlocking tags file...', 'Done.', '']
gutentags: [job output]: ['gtags: /Users/linyue/.cache/tags/Users-linyue-WorkStation-golang_dev-src-git.inke.cn-BackendPlatform-golang/GTAGS seems corrupted.', '']
gutentags: [job output]: ['']
gutentags: [job output]: ['']
gutentags: [job output]: ['ctags: Warning: --extra option is obsolete; use --extras instead', '']
gutentags: [job output]: ['']
gutentags: [job output]: ['']
gutentags: Finished gtags_cscope job.
gutentags: gtags-cscope job failed, returned: 1
```
@ludovicchabant What should I do.

**Comment by gauteh** [comment]
I'm getting this error when ctags outputs some warning about files or directories it is not able to open or parse. Everything else seems to work though. Could it be that ctags just returns non-zero if there is some warning, even though everything is fairly ok?

**Comment by adriand** [comment]
Tag generation is also failing for me. The error message boils down to:

`['ctags: cannot open "/var/folders/w8/qs0nxql90hd6rq04z3dpswhr0000gn/T/nvimlG6s0j/1" : No such file or directory', '']`

The weird part is that this folder - whatever it is and wherever a reference to it is coming from - seems to be passed in as something to **exclude**. I.e. ctags is told to exclude this folder, but then it generates an error saying it can't open it, which doesn't seem to make a lot of sense.

Full message:
```
gutentags: Wildignore options file is up to date.
gutentags: Running: ['/Users/adrianduyzer/.vim/bundle/vim-gutentags/plat/unix/update_tags.sh', '-e', 'ctags', '-t', 'tags', '-p', '.', '-s', 'app/assets/javas
cripts/tenon/features/category_nav.js', '-o', '/Users/adrianduyzer/.vim/bundle/vim-gutentags/res/ctags_recursive.options', '-x', '@/var/folders/w8/qs0nxql90hd
6rq04z3dpswhr0000gn/T/nvimlG6s0j/1', '-l', 'tags.log']
gutentags: In:      /Users/adrianduyzer/Mesa/www/drugs
gutentags: [job stdout]: ['Locking tags file...', 'Removing references to: app/assets/javascripts/tenon/features/category_nav.js', 'grep --text -Ev ''^[^^I]+^
Iapp/assets/javascripts/tenon/features/category_nav.js^I'' ''tags'' > ''tags.temp''', 'Running ctags on "app/assets/javascripts/tenon/features/category_nav.js
"', 'ctags -f "tags.temp"  --options=/Users/adrianduyzer/.vim/bundle/vim-gutentags/res/ctags_recursive.options --exclude=@/var/folders/w8/qs0nxql90hd6rq04z3dp
swhr0000gn/T/nvimlG6s0j/1 --append "app/assets/javascripts/tenon/features/category_nav.js"', '']
gutentags: [job stderr]: ['ctags: cannot open "/var/folders/w8/qs0nxql90hd6rq04z3dpswhr0000gn/T/nvimlG6s0j/1" : No such file or directory', '']
gutentags: [job stderr]: ['']
gutentags: [job stdout]: ['']
gutentags: Finished ctags job.
gutentags: ctags job failed, returned: 1
```

**Comment by unknownbreaker** [comment]
I reinstalled `brew reinstall ctags` and restarted my machine. Still got the error.

I ended up uninstalling `ctags` and installed `brew install universal-ctags`. The error is now gone for me.

I do not need to set the `gutentags_ctags_executable` variable anymore.

**Comment by adamcstephens** [comment]
I'm using https://github.com/universal-ctags/homebrew-universal-ctags and ran into this issue. At some point the brew symlinks went missing, or were never installed.

This fixed it for me

```
brew unlink universal-ctags && brew link universal-ctags
```

**Comment by dagadbm** [comment]
gutentags: Wildignore options file is up to date.
gutentags: Running: ['/Users/david.maia/.config/nvim/plugged/vim-gutentags/plat/unix/update_tags.sh', '-e', 'ctags', '-t', '/Users/david.maia/.gutentags_cache/Users-david.maia-dotf
iles-tags', '-p', '/Users/david.maia/dotfiles', '-s', '/Users/david.maia/dotfiles/vim/init.vim', '-o', '/Users/david.maia/.config/nvim/plugged/vim-gutentags/res/ctags_recursive.opt
ions', '-O', '--tag-relative=yes', '-O', '--fields=+ailmnS', '-x', '*.git', '-x', '*.svn', '-x', '*.hg', '-x', 'cache', '-x', 'build', '-x', 'dist', '-x', 'bin', '-x', 'node_module
s', '-x', 'bower_components', '-x', '*-lock.json', '-x', '*.lock', '-x', '*.min.*', '-x', '*.bak', '-x', '*.zip', '-x', '*.pyc', '-x', '*.class', '-x', '*.sln', '-x', '*.csproj', '
-x', '*.csproj.user', '-x', '*.tmp', '-x', '*.cache', '-x', '*.vscode', '-x', '*.pdb', '-x', '*.exe', '-x', '*.dll', '-x', '*.bin', '-x', '*.mp3', '-x', '*.ogg', '-x', '*.flac', '-
x', '*.swp', '-x', '*.swo', '-x', '.DS_Store', '-x', '*.plist', '-x', '*.bmp', '-x', '*.gif', '-x', '*.ico', '-x', '*.jpg', '-x', '*.png', '-x', '*.svg', '-x', '*.rasdjfoksdokfjewo
ifjdfjofo jf fr', '-x', '*.zip', '-x', '*.tar', '-x', '*.tar.gz', '-x', '*.tar.xz', '-x', '*.tar.bz2', '-x', '*.pdf', '-x', '*.doc', '-x', '*.docx', '-x', '*.ppt', '-x', '*.pptx',
'-x', '*.xls', '-l', '/Users/david.maia/.gutentags_cache/Users-david.maia-dotfiles-tags.log']
gutentags: In:      /Users/david.maia/dotfiles
gutentags: [job stdout]: ['Locking tags file...', 'Removing references to: /Users/david.maia/dotfiles/vim/init.vim', 'grep --text -Ev ''^[^^I]+^I/Users/david.maia/dotfiles/vim/init
.vim^I'' ''/Users/david.maia/.gutentags_cache/Users-david.maia-dotfiles-tags'' > ''/Users/david.maia/.gutentags_cache/Users-david.maia-dotfiles-tags.temp''', 'Running ctags on "/Us
ers/david.maia/dotfiles/vim/init.vim"', 'ctags -f "/Users/david.maia/.gutentags_cache/Users-david.maia-dotfiles-tags.temp" "--options=/Users/david.maia/.config/nvim/plugged/vim-gut
entags/res/ctags_recursive.options"  --tag-relative=yes --fields=+ailmnS --exclude=*.git --exclude=*.svn --exclude=*.hg --exclude=cache --exclude=build --exclude=dist --exclude=bin
 --exclude=node_modules --exclude=bower_components --exclude=*-lock.json --exclude=*.lock --exclude=*.min.* --exclude=*.bak --exclude=*.zip --exclude=*.pyc --exclude=*.class --excl
ude=*.sln --exclude=*.csproj --exclude=*.csproj.user --exclude=*.tmp --exclude=*.cache --exclude=*.vscode --exclude=*.pdb --exclude=*.exe --exclude=*.dll --exclude=*.bin --exclude=
*.mp3 --exclude=*.ogg --exclude=*.flac --exclude=*.swp --exclude=*.swo --exclude=.DS_Store --exclude=*.plist --exclude=*.bmp --exclude=*.gif --exclude=*.ico --exclude=*.jpg --exclu
de=*.png --exclude=*.svg --exclude=*.rasdjfoksdokfjewoifjdfjofo jf fr --exclude=*.zip --exclude=*.tar --exclude=*.tar.gz --exclude=*.tar.xz --exclude=*.tar.bz2 --exclude=*.pdf --ex
clude=*.doc --exclude=*.docx --exclude=*.ppt --exclude=*.pptx --exclude=*.xls --append "/Users/david.maia/dotfiles/vim/init.vim"', '']
gutentags: [job stdout]: ['']
gutentags: [job stderr]: ['ctags: Warning: cannot open input file "jf" : No such file or directory', 'ctags: Warning: cannot open input file "fr" : No such file or directory', 'cta
gs: --append option may not follow a file name', '']
gutentags: [job stderr]: ['']
gutentags: Finished ctags job.


i get this error but only on my dotfiles repo

**Comment by dagadbm** [comment]
LOL nvm. i had some unintended config

**Comment by wonhyukchoi** [comment]
(For posterity) if you are using FreeBSD, doing `pkg install ctags` _does not_ place exuberant ctags in `/usr/bin/ctags`. 
You can instead do
```sh
sudo ln -s /usr/local/bin/exctags /usr/bin/ctags
```

**Comment by SuperPhone111** [comment]
Hi 
I follow this comment https://github.com/ludovicchabant/vim-gutentags/issues/169#issuecomment-624914471, but it still not work.
I use "Exuberant Ctags"
```
$ ctags --version
Exuberant Ctags 5.9~svn20110310, Copyright (C) 1996-2009 Darren Hiebert
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex
```
 
Here is my fail logs:
```
"init/main.c" 1184L, 29543C                                                                                                                                                                                 
gutentags: Scanning buffer 'init/main.c' for gutentags setup...                                                                                                                                             
gutentags: No specific project type.                                                                                                                                                                        
gutentags: Setting gutentags for buffer 'init/main.c'                                                                                                                                                       
gutentags: Generating tags file: /home/derek/.cache/tags/home-derek-tiny4412-linux-4.20.7-.tags                                                                                                               
gutentags: Wildignore options file is up to date.                                                                                                                                                           
gutentags: Running: ['/home/derek/.vim/bundle/vim-gutentags/plat/unix/update_tags.sh', '-e', 'ctags', '-t', '/home/derek/.cache/tags/home-derek-tiny4412-linux-4.20.7-.tags', '-p', '/home/derek/tiny4412/linux-
4.20.7', '-o', '/home/derek/.vim/bundle/vim-gutentags/res/ctags_recursive.options', '-O', '--fields=+niazS', '-O', '--extra=+q', '-O', '--c++-kinds=+px', '-O', '--c-kinds=+px', '-O', '--output-format=e-cta
gs', '-l', '/home/derek/.cache/tags/home-derek-tiny4412-linux-4.20.7-.tags.log']                                                                                                                              
gutentags: In:      /home/derek/tiny4412/linux-4.20.7                                                                                                                                                        
gutentags: Generating tags file: /home/derek/.cache/tags/home-derek-tiny4412-linux-4.20.7/GTAGS                                                                                                               
gutentags: Running: ['gtags', '--incremental', '/home/derek/.cache/tags/home-derek-tiny4412-linux-4.20.7']                                                                                                    
gutentags: In:      /home/derek/tiny4412/linux-4.20.7                                                                                                                                                        
gutentags:                                                                                                                                                                                                  
gutentags: [job stdout]: 'Locking tags file...'                                                                                                                                                             
gutentags: [job stdout]: 'Running ctags on whole project'                                                                                                                                                   
gutentags: [job stdout]: 'ctags -f "/home/derek/.cache/tags/home-derek-tiny4412-linux-4.20.7-.tags.temp" "--options=/home/derek/.vim/bundle/vim-gutentags/res/ctags_recursive.options"  --fields=+niazS --extra
=+q --c++-kinds=+px --c-kinds=+px --output-format=e-ctags "/home/derek/tiny4412/linux-4.20.7"'                                                                                                               
gutentags: [job stderr]: 'ctags: Unknown option: --output-format'                                                                                                                                           
gutentags: Finished ctags job.                                                                                                                                                                              
gutentags: ctags job failed, returned: 1        
```

**Comment by adampaulukanis** [comment]
Hi, maybe late to the party. 

I am on OpenBSD 7.3.
The problem in my case was the file `.../vim/pack/$XYZ/start/vimgutentags/res/ctags_recursive.options`.  I was symlinking it with my `~/.ctags` but it did not work. I had to copy that file over.

**Comment by maieul** [comment]
I have the same problem, but only with some kind of file. LaTeX files don't work, PHP files work.

**Comment by maieul** [comment]
And the problem in my case was a conflict between universal-ctags and exuberant-ctags.

A did a `apt remove exuberant-ctags` and now all work.
